# Generated by Django 4.2.5 on 2023-09-14 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expectedDue',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 20, 52, 40, 229880)),
        ),
    ]
