# Generated by Django 4.2.5 on 2023-09-14 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_book_borrow_book_alter_borrow_expecteddue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='expectedDue',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 21, 29, 38, 619986)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
