# Generated by Django 4.2.5 on 2023-09-14 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrow_expecteddue_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='expectedDue',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 22, 21, 24, 103061)),
        ),
    ]
